services:
  iris-em:
    build:
      context: ./IRIS/latest-em
      args:
        - IMAGE=${IMAGE_IRIS_EM}
    # image: ${IMAGE_IRIS_EM} # EXTENDED MAINTENANCE
    init: true
    container_name: ${CONTAINER_IRIS_EM}
    hostname: ${CONTAINER_IRIS_EM}
    volumes:
    - type: bind
      source: ./IRIS
      target: /IRIS
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - type: bind
      source: ./volumes
      target: /volumes
    command: --key /IRIS/key/iris.key -a /IRIS/configure_default_password.sh
    # command: --key /IRIS/key/iris.key -a /IRIS/configure_change_password.sh
    ports:
      - 11004:1972
    environment:
      - ISC_DATA_DIRECTORY=/volumes/${EXTENDED_MAINTENANCE}
      # - TZ=Europe/Paris

  iris-cd:
    build:
      context: ./IRIS/latest-cd
      args:
        - IMAGE=${IMAGE_IRIS_CD}
    # image: ${IMAGE_IRIS_CD} # CONTINUOUS DELIVERY
    init: true
    container_name: ${CONTAINER_IRIS_CD}
    hostname: ${CONTAINER_IRIS_CD}
    volumes:
    - type: bind
      source: ./IRIS
      target: /IRIS
    # - "/etc/timezone:/etc/timezone:ro"
    # - "/etc/localtime:/etc/localtime:ro"
    - type: bind
      source: ./volumes
      target: /volumes
    command: --key /IRIS/key/iris.key -a /IRIS/configure_default_password.sh
    # command: --key /IRIS/key/iris.key -a /IRIS/configure_change_password.sh
    ports:
      - 11005:1972
    environment:
      - ISC_DATA_DIRECTORY=/volumes/${CONTINUOUS_DELIVERY}
      - TZ=Europe/Paris

  iris-preview:
    build:
      context: ./IRIS/latest-preview
      args:
        - IMAGE=${IMAGE_IRIS_PREVIEW}
    # image: ${IMAGE_IRIS_PREVIEW} # DEVELOPER PREVIEW
    init: true
    container_name: ${CONTAINER_IRIS_PREVIEW}
    hostname: ${CONTAINER_IRIS_PREVIEW}
    volumes:
    - type: bind
      source: ./IRIS
      target: /IRIS
    # - "/etc/timezone:/etc/timezone:ro"
    # - "/etc/localtime:/etc/localtime:ro"
    - type: bind
      source: ./volumes
      target: /volumes
    command: --key /IRIS/key/iris.key -a /IRIS/configure_default_password.sh
    # command: --key /IRIS/key/iris.key -a /IRIS/configure_change_password.sh
    ports:
      - 11006:1972
    environment:
      - ISC_DATA_DIRECTORY=/volumes/${DEVELOPER_PREVIEW}
      - TZ=Europe/Paris

  webgateway:
    image: ${WEBGATEWAY}
    init: true
    hostname: ${WEBGATEWAY_NAME}
    ports:
    - ${WEBGATEWAY_PORT_HTTP}:80
    - ${WEBGATEWAY_PORT_HTTPS}:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway/CSP.ini
    volumes:
    - type: bind
      source: ./webgateway
      target: /webgateway